// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Column } from "./Column";
import type { SqlValue } from "./SqlValue";

export type ListRowsResponse = { total_row_count: bigint, cursor: string | null, columns: Array<Column>, rows2: Array<Array<SqlValue>>, };
